config/routes.rb
CodeCollector::Application.routes.draw do
  resources :articles do
    get :edit_content, :on => :member
  end
  resources :courses
  resources :categories

  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  belongs_to :course

  # default_scope order("updated_at DESC")
  scope :category_with, lambda { |category| where(:category_id => category) }

  attr_accessible(
    :content,
    :summary,
    :title,
    :category_id,
    :course_id,
    :screenshot,
    :video,
    :tag_list,
    :privated
  )
  mount_uploader :screenshot, ImageUploader
  acts_as_taggable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article
    @articles = @articles.tagged_with(params[:tag]) if params[:tag]
    @articles = @articles.category_with(params[:category]) if params[:category]
    @articles = @articles.order('id DESC').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        if params[:commit] == "Save Article and Edit Content"
          format.html { redirect_to edit_content_article_path(@article), notice: 'Article was successfully updated.' }
        else
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        end
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        if params[:commit] == "Save Article and Edit Content"
          format.html { redirect_to edit_content_article_path(@article), notice: 'Article was successfully updated.' }
        else
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_content
    @article = Article.find(params[:id])
    render :layout => false
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ["code", language, sha].join('-') do
        Pygments.highlight(code, lexer: language, options: { linespans: 'line' })
      end
    end

    # Extend the Redcarpet 2 Markdown library.
    # http://dev.af83.com/2012/02/27/howto-extend-the-redcarpet2-markdown-lib.html
    # Inlcude ActionView::Helpers::TagHelper so we can use content_tag method.
    include ActionView::Helpers::TagHelper
    def block_quote(quote)
      content_tag(:blockquote, content_tag(:div, quote.html_safe, class: 'quote'))
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    # If text(means article content) is nil, there will be wrong argument type nil (expected String).
    # so make text || ""
    Redcarpet::Markdown.new(renderer, options).render(text || "").html_safe
  end

  def layout_with_screenshot(article)
    "span10" if article.screenshot?
  end

  def show_tag_name_warp_by_span(tag_list, tag)
    class_name = tag_list.include?(tag.name) ? "label label-success" : "label"
    content_tag(:span, tag.name, :class => class_name)
  end

  def tag_list_with_link(article)
    text =  ""
    article.tags.each do |tag|
      text << "#{link_to tag.name, articles_path(tag: tag.name)}"
    end
    text.html_safe
  end
end

app/views/articles/_content.html.erb
<div class="article_content">
  <% if !authorize? && @article.privated  %>
    <%= 'It\'s a secret' %>
  <% else  %>
    <%= markdown(@article.content) %>
  <% end %>
</div><!-- #article_content -->

app/views/articles/_form.html.haml
= simple_form_for(@article, :html => {:multipart => true}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :category_id, collection: @article_categories.map { |c| [c.name, c.id] }, prompt: "Chooses a category"
    = f.input :course_id, collection: Course.all.map { |c| [c.title, c.id] }, prompt: "Chooses a course", input_html: { class: 'span6' }
    = f.input :title, input_html: { class: 'span12' }
    = f.input :summary, input_html: { class: 'span12', rows: 4 }
    = f.input :tag_list, input_html: { class: 'span12' }
    #all_tags_for_article.control-group
      .controls
        - @tags.each do |tag|
          = render :partial => 'shared/tag', :locals => { :tag_list => @article.tag_list, :tag => tag }

    = f.input :video, input_html: { class: 'span12', rows: 4 }

    .control-group
      .controls
        = image_tag(@article.screenshot_url) if @article.screenshot?
    = f.input :screenshot, wrapper_html: { class: 'hide' }
    .control-group
      .input-append
        %label.control-label{for: "screenshot"} Screenshot
        .controls
          = text_field_tag "screenshotCover", @article.screenshot_url, class: "input-xxlarge"
          = link_to "Browse", "javascript:void(0)", class: "browse_btn btn"

    = f.input :privated

  .form-actions
    = f.button :submit
    = f.submit 'Save Article and Edit Content', class: 'btn btn-primary'

app/views/articles/_syntax_cheatsheet.html.erb
<!-- Modal -->
<div id="syntax_cheatsheet" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Syntax Cheatsheet</h3>
  </div>
  <div class="modal-body">
    <%= render "shared/syntax_cheatsheet" %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/articles/edit.html.haml
.article_title.clearfix
  %h1 Editing article
  = link_to content_tag(:span, content_tag(:i, nil, class: 'icon-share icon-white') + ' Show', class: 'label label-info'), @article, class: "show_article"
  = link_to content_tag(:span, content_tag(:i, nil, class: 'icon-edit icon-white') + ' Update Content', class: 'label label-info'), edit_content_article_path(@article), class: "edit_article_content"  
= render 'form'

app/views/articles/edit_content.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Markdown Editor</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>  
  
  <!-- https://github.com/jbt/markdown-editor -->
  <%= javascript_include_tag "marked" %>
  <%= javascript_include_tag "highlight.pack.js" %>  
  <%= javascript_include_tag "codemirror/lib/codemirror" %>    
  <%= javascript_include_tag "codemirror/xml/xml" %>
  <%= javascript_include_tag "codemirror/markdown/markdown" %>
  <%= javascript_include_tag "codemirror/gfm/gfm" %>  
  <%= javascript_include_tag "codemirror/javascript/javascript" %>    
  <%= javascript_include_tag "rawinflate" %>  
  <%= javascript_include_tag "rawdeflate" %>    
  <%= stylesheet_link_tag "codemirror/lib/codemirror" %>
  <%= stylesheet_link_tag "tomorrow.theme" %>
  <!-- Custom markdown-editor page style and init markdown editor. -->  
  <%= stylesheet_link_tag "init_markdown_editor" %>   
</head>
<body>
  <div id="in">
    <%= form_for @article do |f| %>
      <%= f.text_area(:content, :id => 'code')%>
      <%= submit_tag "Save", id: "save_content_btn", style: "display:none" %>  
    <% end %>
  </div>
  <div id="out"></div>
  <div id="edit_content_footer">
    <%= link_to "Save", "javascript:void(0)", class: "btn btn-mini btn-primary", id: "save_btn" %>
    <a href="#syntax_cheatsheet" role="button" class="btn btn-mini" data-toggle="modal">Help</a>
    <%= link_to "Back", article_path(@article), class: 'btn btn-mini' %>
  </div>
  <%= render "articles/syntax_cheatsheet" %>
  <%= javascript_include_tag "init_markdown_editor" %>  
  <script type="text/javascript" charset="utf-8">
    $(function() {
      $("#save_btn").click(function() {
        $("form").submit();
      })
    })
  </script>
</body>
</html>

app/views/articles/index.html.haml
.article_listing.clearfix
  %h1 Listing articles
  - @articles.each do |article|
    .article_wrap.row
      .text_warp{ class: layout_with_screenshot(article)}
        .article_title_wrap.clearfix
          %span.number= "##{article.id}"
          %h2= link_to article.title, article
          %span.date
            %i.icon-time
            = article.updated_at.to_s(:nice_time)
          %span.tags
            %i.icon-tags
            = tag_list_with_link(article)
      
        .article_summary_wrap
          = article.summary
          
      - if article.screenshot?
        .image_warp.span2
          %div
            = link_to image_tag(article.screenshot_url), article

= paginate @articles
.page_entries_info= page_entries_info @articles

app/views/articles/new.html.haml
%h3 New article

= render 'form'

app/views/articles/show.html.haml
.article_title.clearfix
  %h1
    %span= "##{@article.id}"
    = @article.title
  - if authorize?
    = link_to content_tag(:span, content_tag(:i, nil, class: 'icon-edit icon-white') + ' Edit', class: 'label label-info'), edit_article_path(@article), class: "edit_article"
    = link_to content_tag(:span, content_tag(:i, nil, class: 'icon-edit icon-white') + ' Update Content', class: 'label label-info'), edit_content_article_path(@article), class: "edit_article_content"
.article_summary
  .row
    .tags
      Tags:
      - @article.tags.each do |tag|
        = link_to tag.name, articles_path(tag: tag.name)
    .download
      = link_to content_tag(:span, content_tag(:i, nil, class: 'icon-download-alt icon-white') + ' Download Video', class: 'label label-success'), @article.video, target: "_blank" unless @article.video.blank?
  - unless @article.summary.blank?
    .summary= simple_format @article.summary

= render "content"