config/routes.rb
CodeCollector::Application.routes.draw do
  resources :articles do
    get :edit_content, :on => :member
  end
  resources :courses
  resources :categories

  root :to => 'articles#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  has_many :courses

  attr_accessible :name, :type_name

  default_scope order(:id)
  scope :for_article, where(:type_name => "Article")
  scope :for_course, where(:type_name => "Course")

  TYPES = ["Article", "Course"]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, input_html: { class: 'span6' }
    = f.input :type_name, :collection => Category::TYPES, prompt: "Select a type"

  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h3 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h3 Listing categories

%table.table.table-striped.table-bordered
  %tr
    %th.span8 Name
    %th Type
    %th

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= category.type_name
      %td
        = link_to 'Show', category, class: 'btn btn-mini'
        = link_to 'Edit', edit_category_path(category), class: 'btn btn-mini'
        = link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'

%p
  = link_to 'New Category', new_category_path, class: 'btn btn-mini btn-primary'

app/views/categories/new.html.haml
%h3 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Type:
  = @category.type_name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path