config/routes.rb
CodeCollector::Application.routes.draw do
  resources :articles do
    get :edit_content, :on => :member
  end
  resources :courses
  resources :categories

  root :to => 'articles#index'

end

app/views/layouts/_footer.html.haml
#footer_wrap
  #footer
    %p Version:1.0.0

app/views/layouts/_header.html.haml
#header_wrap
  #header.clearfix
    %h1= link_to "Code Collector", "/"
    - if authorize?
      %ul
        %li= link_to_unless_current "Articles", articles_path
        %li= link_to_unless_current "Courses", courses_path
        %li= link_to_unless_current "New Article", new_article_path
        %li= link_to_unless_current "New Course", new_course_path
        %li= link_to_unless_current "New Category", new_category_path

app/views/layouts/_sidebar.html.haml
#side_content.span3
  - if show_syntax_cheatsheet?
    = render "layouts/syntax_cheatsheet"
  - if show_categories?
    .course_categories
      %h2 Course Categories
      %ul
        - @course_categories.each do |category|
          %li
            = link_to category.name, courses_path(category: category)
            %span.badge= category.courses.count
        %li.show_all= link_to "All Course", courses_path

    .categories
      %h2 Article Categories
      %ul
        - @article_categories.each do |category|
          %li
            = link_to category.name, articles_path(category: category)
            %span.badge= category.articles.count
        %li.show_all= link_to "All Articles", articles_path

    .tags
      %h2 Tags
      %ul
        - @tags.each do |tag|
          = link_with_tag(@articles, @courses, tag.name)

app/views/layouts/_syntax_cheatsheet.html.erb
<div class="syntax_cheatsheet">
  <h2>Syntax Cheatsheet</h2>
  <div class="syntax_cheatsheet_content">
    <%= render "shared/syntax_cheatsheet" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeCollector</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= favicon_link_tag "favicon.ico" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div id="container">
    <%= render "layouts/header" %>
    <div id="content_wrap">
      <div id="content">
        <div class="container-fluid">
          <div class="row-fluid">
            <div id="main_content" class="span9">
              <!-- here is main content -->
              <%= yield %>
            </div>
            <%= render "layouts/sidebar" %>
          </div>
        </div>
      </div>
    </div><!-- #content_wrap -->
    <%= render "layouts/footer" %>
  </div>
  <%= javascript_include_tag "application" %>
</body>
</html>